apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: nikolay.s.vaklinov@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: private-key
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.deployment.domain }}
      dns01:
        route53:
          region: eu-central-1

#flux create secret git flask-auth \
#    --url=ssh://git@github.com/nvaklinov/flask-project.git \
#    --private-key-file=./id_rsa

