apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: andi_dd1@yahoo.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: private-key
    solvers:
    - selector:
        dnsZones:
          - "andydim.click"
      dns01:
        route53:
          region: eu-central-1